repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: detect-private-key

  - repo: local
    hooks:
      - id: black
        name: black
        entry: ./venv/bin/black
        language: system
        types: [python]

      - id: pylint
        name: pylint
        entry: ./venv/bin/pylint
        language: system
        types: [python]
        args: ["--rcfile=pyproject.toml"]

      - id: mypy
        name: mypy
        entry: ./venv/bin/mypy
        language: system
        types: [python]

      - id: pip-audit
        name: pip-audit
        entry: ./venv/bin/pip-audit
        language: system
        pass_filenames: false
